### ISSUE TITLE
Update to current Reveal.js version

### ISSUE THREAD

**Issue by rajgoel** [matbury/mod_revealjs#4]
The reveal.js version in the repository is already 2 years old and the original repository has seen quite a few newer versions since then (and will likely see others in the future). It would be good to have instructions in the Readme.md on how to upgrade reveal.js to the most recent version. In particular it would be good to separate reveal.js-files from the moodle plugin-files, so that there is no risk of messing up files.

Does the plugin still work with reveal.js 3.1?

**Comment by matbury** [comment]
Hi Raj, yes I'm working on a new version for reveal.js 3.x. It may not be backwardly compatible though. That's the bit that's taking a while. I'm pretty busy at the moment so please be patient :)
