### ISSUE TITLE
Demo course not available?

### ISSUE THREAD

**Issue by lechten** [matbury/mod_revealjs#8]
The readme mentions a demo course: https://matbury.com/moodle/course/view.php?id=2
I created an account, but only see this message: Der Kurs steht aktuell für Teilnehmer/innen nicht zur Verfügung. (My translation: Course is currently not available for participants.)

In absence of a demo: Is the functionality of this plugin different from importing a zipfile with reveal.js resources using the [file module](https://docs.moodle.org/37/en/File_resource_settings#Displaying_a_website_index_page)?

**Comment by iliasioannou** [comment]
> The readme mentions a demo course: https://matbury.com/moodle/course/view.php?id=2
> I created an account, but only see this message: Der Kurs steht aktuell für Teilnehmer/innen nicht zur Verfügung. (My translation: Course is currently not available for participants.)
> 
> In absence of a demo: Is the functionality of this plugin different from importing a zipfile with reveal.js resources using the [file module](https://docs.moodle.org/37/en/File_resource_settings#Displaying_a_website_index_page)?


How is this suppose to work? Do i have to upload a priori the files in a specified folder?

![image](https://user-images.githubusercontent.com/3886244/82444030-d8bf0c00-9aa2-11ea-82c0-3afcf648e335.png)
